artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file:  iris_data/iris.data
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/iris.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  image_path: artifacts/data_validation/images


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/iris.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: irispred.joblib
  
